### ISSUE TITLE
current-average-price not available 

### ISSUE THREAD

**Issue by chromafunk** [niXman/binapi#44]
Thank you for this amazing work ! 

Is there any reason why is this not implemented on the lib ? 

https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#current-average-price

I think it's pretty useful :)

**Comment by niXman** [comment]
can you implement it please?

**Comment by chromafunk** [comment]
sure ! give me some time and I'll post a PR

**Comment by niXman** [comment]
done: https://github.com/niXman/binapi/commit/f75c951656692019fea20ca95f86808d0421a691

thanks

**Comment by chromafunk** [comment]
hey that was fast ! sorry but I have been burdened trying to figure out why the trades ws stream drifts in time ... for some reason, I believe when the frequency of messages is high, messages accumulate and time starts drifting ... have you experienced this ? I am still not sure why this happens and trying to measure it. In case you have experienced it, how are you supposed to deal with this ? Does one need to drop messages that don't match with current exchange time perhaps ? Thank you

**Comment by niXman** [comment]
> hey that was fast !

I spent 20 minutes on this.

> sorry but I have been burdened trying to figure out why the trades ws stream drifts in time ... for some reason, I believe when the frequency of messages is high, messages accumulate and time starts drifting ... have you experienced this ? I am still not sure why this happens and trying to measure it. In case you have experienced it, how are you supposed to deal with this ? Does one need to drop messages that don't match with current exchange time perhaps ? In case you haven't measured this yet, I am doing it and I will post my findings. But it's kind of critical since the drift on time ( out of sync ) gets severe, sometimes it's 1 minute apart. Thank you

please create a separate issue with code example.
